version: '3.7'

services:
  swarm:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./docker/etc/reactivedrop:/etc/reactivedrop"
      - "./docker/usr/local/bin:/usr/local/bin"
    ports:
      - "8080:8080"
      - "27015:27015"
    networks:
      - network

networks:
  network:
