version: '3.7'

services:
  swarm:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./docker/usr/local/bin:/usr/local/bin"
    ports:
    - "28001:28001"
    networks:
      - network

networks:
  network:
