version: '3.7'

services:
  swarm:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./bin:/usr/local/bin"
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
      - target: 28001
        published: 28001
        protocol: tcp
        mode: host
      - target: 28002
        published: 28002
        protocol: tcp
        mode: host
    environment:
      - "rd_server_1_port=28001"
      - "rd_server_1_hostname=My First Server"
      - "rd_sourcebans_1_id=1"
      - "rd_server_2_port=28002"
      - "rd_server_2_hostname=My Second Server"
      - "rd_sourcebans_2_id=2"
      - "sourcemod_admin_steamid=12345"
      - "sourcebans_host=127.0.0.1"
      - "sourcebans_port=3306"
      - "sourcebans_user=myuser"
      - "sourcebans_password=mysecret"
      - "sourcebans_database=sourcebans"
    networks:
      - network

networks:
  network:
