version: 2.1
jobs:
  build:
    working_directory: ~/repo
    resource_class: small
    docker:
      - image: circleci/buildpack-deps:stable
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Connect to Docker Hub
          command: docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
      - restore_cache:
          keys:
            - v1-last-build-{{ .Branch }}
          paths:
            - .last-build-version
      - restore_cache:
          keys:
            - v1-docker-layers-{{ .Branch }}
          paths:
            - /tmp/caches/app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /tmp/caches/app.tar | true
      - run:
          name: Build images
          command: |
            build/container release --push
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /tmp/caches
            docker save -o /tmp/caches/app.tar mithrand0/reactive-drop-server
      - save_cache:
          key: v1-docker-layers-{{ .Branch }}
          paths:
            - /tmp/caches/app.tar
      - save_cache:
          key: v1-last-build-{{ .Branch }}
          paths:
            - .last-build-version
  rebuild:
    working_directory: ~/repo
    resource_class: small
    docker:
      - image: circleci/buildpack-deps:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Connect to Docker Hub
          command: docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
      - run:
          name: Build images
          command: |
            build/container all --push

# workflow for this project
workflows:
  version: 2
  build:
    jobs:
      - build:
          context: build
      - rebuild:
          type: approval
          context: build
          requires:
            - build
