version: 2.1
jobs:
  build:
    working_directory: ~/repo
    resource_class: small
    docker:
      - image: circleci/buildpack-deps:stable
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v2-{{ .Branch }}
          paths:
            - .last-build-version
      - run:
          name: Build images
          command: |
            build/container release
      - save_cache:
          key: v2-{{ .Branch }}
          paths:
            - .last-build-version

  rebuild:
    working_directory: ~/repo
    resource_class: small
    docker:
      - image: circleci/buildpack-deps:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build images
          command: |
            build/container all

# workflow for this project
workflows:
  version: 2
  build:
    jobs:
      - build:
          context: build
      - rebuild:
          type: approval
          requires:
            - build
